[package]
name = "smtp-notifier"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
pulsar-core = { workspace = true }

tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
lettre = { workspace = true }
leon = { workspace = true }
gethostname = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }

[features]
default = ["native-tls"]

# TLS
boring-tls = ["lettre/tokio1-boring-tls"]
native-tls = ["lettre/tokio1-native-tls"]
rustls-tls = ["lettre/tokio1-rustls-tls"]
